### ISSUE TITLE
wrong json format many mistakes (no commas etc)

### ISSUE THREAD

**Issue by arpitjha867** [aryanvar/Cricketers-Info#56]
https://github.com/aryanvar/Cricketers-Info/blob/1f0ef64d136155c62eb83ff00fbb86d1c60f2276/index.json#L112

**Comment by arpitjha867** [comment]
assign this is issue to me

**Comment by arpitjha867** [comment]
i have corrected the json file and made the pull request for the same so please review it and merge the pull request

**Comment by aryanvar** [comment]
i did all the possiable correction after yours
